import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { AuditEntry, Report } from './types';
import { RiskLevel, RISK_WEIGHTS } from '@resimantle/types';
import { COMMON_CONSTANTS } from '../../common/constants';
import { logger } from '../../common/logger';

type ReportFormat = 'md' | 'json' | 'both';

const REPORT_FORMATS = new Set<ReportFormat>(['md', 'json', 'both']);

/**
 * Generates comprehensive security reports from audit data.
 * Supports both Markdown (human-readable) and JSON (machine-readable) output.
 */
export class Reporter {
  private entries: AuditEntry[];
  private outputDir: string;

  constructor(entries: AuditEntry[], resiMantleDir: string) {
    this.entries = entries;
    this.outputDir = resiMantleDir;
  }

  /**
   * Generates a beautiful Markdown report.
   */
  async generateMarkdown(): Promise<string> {
    const now = new Date();
    const severityCounts = this.countBySeverity();
    const totalRisk = this.calculateOverallRisk();

    const riskEmoji: Record<string, string> = {
      [RiskLevel.NONE]: '🟢',
      [RiskLevel.INFO]: '🔵',
      [RiskLevel.LOW]: '🟡',
      [RiskLevel.MEDIUM]: '🟠',
      [RiskLevel.HIGH]: '🔴',
      [RiskLevel.CRITICAL]: '🚨',
    };

    let md = '';

    // Header
    md += `# 🛡️ ResiMantle Security Report\n\n`;
    md += `**Generated:** ${now.toISOString()}\n`;
    md += `**Version:** ${COMMON_CONSTANTS.VERSION}\n`;
    md += `**Overall Risk:** ${riskEmoji[totalRisk] || '❓'} **${totalRisk}**\n\n`;

    // Summary Table
    md += `## Summary\n\n`;
    md += `| Severity | Count |\n`;
    md += `|----------|-------|\n`;
    for (const level of [RiskLevel.CRITICAL, RiskLevel.HIGH, RiskLevel.MEDIUM, RiskLevel.LOW, RiskLevel.INFO, RiskLevel.NONE]) {
      const count = severityCounts[level] || 0;
      if (count > 0) {
        md += `| ${riskEmoji[level]} ${level} | ${count} |\n`;
      }
    }
    md += `\n**Total findings:** ${this.entries.length}\n\n`;

    // Detailed Findings by Severity
    md += `---\n\n`;
    md += `## Detailed Findings\n\n`;

    // Critical findings first
    for (const severity of [RiskLevel.CRITICAL, RiskLevel.HIGH, RiskLevel.MEDIUM, RiskLevel.LOW, RiskLevel.INFO]) {
      const filtered = this.entries.filter(e => e.event.severity === severity);
      if (filtered.length === 0) continue;

      md += `### ${riskEmoji[severity]} ${severity} (${filtered.length})\n\n`;

      for (const entry of filtered) {
        md += `#### ${entry.event.type}\n`;
        md += `- **Source:** ${entry.event.source}\n`;
        md += `- **Time:** ${entry.event.timestamp}\n`;

        if (entry.explanation) {
          md += `- **Details:** ${entry.explanation}\n`;
        }

        // Include relevant details
        const details = entry.event.details;
        if (details.actorId) md += `- **Actor:** ${details.actorId}\n`;
        if (details.sessionId) md += `- **Session:** ${details.sessionId}\n`;
        if (details.storyId) md += `- **Story:** ${details.storyId}\n`;
        if (details.assetId) md += `- **Asset:** ${details.assetId}\n`;
        if (details.resource) md += `- **Resource:** ${details.resource}\n`;
        if (details.overlayKind) md += `- **Overlay:** ${details.overlayKind}\n`;
        if (details.planId) md += `- **Plan:** ${details.planId}\n`;
        if (details.sinkRecordId) md += `- **Shadow Sink:** ${details.sinkRecordId}\n`;
        if (details.file) md += `- **File:** \`${details.file}\`\n`;
        if (details.line) md += `- **Line:** ${details.line}\n`;
        if (details.evidence) md += `- **Evidence:** \`${details.evidence}\`\n`;
        if (details.recommendation) md += `- **Fix:** ${details.recommendation}\n`;

        if (entry.decision) {
          md += `- **Decision:** ${entry.decision}\n`;
        }

        md += `\n`;
      }
    }

    // Footer
    md += `---\n\n`;
    md += `*Report generated by [ResiMantle](https://github.com/resimantle) v${COMMON_CONSTANTS.VERSION} — Adaptive security resin for AI-era software.*\n`;

    return md;
  }

  /**
   * Generates a structured JSON report.
   */
  async generateJson(): Promise<Report> {
    return {
      title: 'ResiMantle Security Report',
      generatedAt: new Date().toISOString(),
      version: COMMON_CONSTANTS.VERSION,
      summary: this.buildSummary(),
      overallRisk: this.calculateOverallRisk(),
      severityCounts: this.countBySeverity(),
      totalFindings: this.entries.length,
      events: this.entries,
    };
  }

  /**
   * Writes the report to disk in the specified format.
   */
  async writeToDisk(format: ReportFormat = 'both'): Promise<string[]> {
    const validatedFormat = normalizeReportFormat(format);

    if (!existsSync(this.outputDir)) {
      await mkdir(this.outputDir, { recursive: true });
    }

    const written: string[] = [];

    if (validatedFormat === 'md' || validatedFormat === 'both') {
      const md = await this.generateMarkdown();
      const mdPath = join(this.outputDir, 'report.md');
      await writeFile(mdPath, md, 'utf-8');
      written.push(mdPath);
      logger.info(`Markdown report written to ${mdPath}`);
    }

    if (validatedFormat === 'json' || validatedFormat === 'both') {
      const json = await this.generateJson();
      const jsonPath = join(this.outputDir, 'report.json');
      await writeFile(jsonPath, JSON.stringify(json, null, 2), 'utf-8');
      written.push(jsonPath);
      logger.info(`JSON report written to ${jsonPath}`);
    }

    return written;
  }

  // ── Internal ──────────────────────────────────────────────────────────────

  private countBySeverity(): Record<string, number> {
    const counts: Record<string, number> = {};
    for (const entry of this.entries) {
      counts[entry.event.severity] = (counts[entry.event.severity] || 0) + 1;
    }
    return counts;
  }

  private calculateOverallRisk(): RiskLevel {
    if (this.entries.length === 0) return RiskLevel.NONE;

    let maxRisk = RiskLevel.NONE;
    let maxWeight = 0;

    for (const entry of this.entries) {
      const weight = RISK_WEIGHTS[entry.event.severity as RiskLevel] ?? 0;
      if (weight > maxWeight) {
        maxWeight = weight;
        maxRisk = entry.event.severity as RiskLevel;
      }
    }

    return maxRisk;
  }

  private buildSummary(): string {
    const counts = this.countBySeverity();
    const parts: string[] = [];

    if (counts[RiskLevel.CRITICAL]) parts.push(`${counts[RiskLevel.CRITICAL]} critical`);
    if (counts[RiskLevel.HIGH]) parts.push(`${counts[RiskLevel.HIGH]} high`);
    if (counts[RiskLevel.MEDIUM]) parts.push(`${counts[RiskLevel.MEDIUM]} medium`);
    if (counts[RiskLevel.LOW]) parts.push(`${counts[RiskLevel.LOW]} low`);
    if (counts[RiskLevel.INFO]) parts.push(`${counts[RiskLevel.INFO]} informational`);

    if (parts.length === 0) return 'No security issues found. Clean scan!';
    return `Found ${this.entries.length} issue(s): ${parts.join(', ')}.`;
  }
}

function normalizeReportFormat(format: string): ReportFormat {
  const normalized = format.toLowerCase() as ReportFormat;
  if (!REPORT_FORMATS.has(normalized)) {
    throw new Error(`Unsupported report format: ${format}. Use one of: md, json, both.`);
  }
  return normalized;
}
